import React, { useMemo, useState } from 'react';
import { motion } from 'motion/react';
import { ArrowRight, Check, Scissors, Sparkles } from 'lucide-react';
import { createAtelierCommission, GARMENT_OPTIONS, measurementFields } from '../lib/services/atelierService';

const STEPS = ['Identity', 'Measurements', 'Style', 'Confirm'];
const FABRICS = ['Aso-Oke', 'Ankara', 'Adire Silk', 'Heritage Linen', 'Kente Blend', 'Kente Gold'];
const BODY_TYPES = ['athletic', 'slim', 'regular', 'full'];
const FIT_PREFS = ['slim', 'regular', 'relaxed', 'oversized'];
const INITIAL = { gender: 'female', garmentType: 'dress', bodyType: 'regular', fitPreference: 'regular', bust_chest: '', waist: '', hips: '', shoulder: '', length: '', sleeve_length: '', inseam: '', thigh: '', ankle: '', neck: '', arm_length: '', fabric: '', color: '', occasion: '', specialInstructions: '' };

export default function Atelier() {
  const [step, setStep] = useState(1);
  const [profile, setProfile] = useState(INITIAL);
  const [submitting, setSubmitting] = useState(false);
  const [success, setSuccess] = useState(null);
  const garmentOptions = GARMENT_OPTIONS[profile.gender];
  const fields = useMemo(() => measurementFields(profile.gender, profile.garmentType), [profile.gender, profile.garmentType]);
  const update = (key, value) => setProfile((p) => ({ ...p, [key]: value }));
  const changeGender = (gender) => setProfile((p) => ({ ...p, gender, garmentType: GARMENT_OPTIONS[gender][0].value }));

  const submit = async () => {
    setSubmitting(true); setSuccess(null);
    try { const order = await createAtelierCommission(profile); setSuccess(order); setProfile(INITIAL); setStep(1); }
    catch (error) { console.error(error); alert(error?.message || 'Submission failed. Please sign in and try again.'); }
    finally { setSubmitting(false); }
  };

  return <motion.main initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="min-h-screen bg-daraja-charcoal pt-28 pb-24 px-6 md:px-12">
    <div className="max-w-6xl mx-auto grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-16">
      <section className="lg:col-span-5 space-y-8">
        <header className="space-y-4"><div className="flex items-center gap-3 text-daraja-gold mono-text text-[10px]"><Scissors className="w-4 h-4" /><span>ATELIER_COMMISSION_PROTOCOL</span></div><h1 className="text-5xl md:text-7xl font-serif italic text-white tracking-tighter">Identity <span className="text-daraja-gold not-italic">Node</span></h1><p className="text-white/50 font-serif text-lg">A bespoke commission built around your body profile, garment and craft preferences.</p></header>
        <div className="luxury-card p-8 space-y-8"><div className="flex items-center justify-between">{STEPS.map((label, i) => <div key={label} className={`flex flex-col items-center gap-2 ${step >= i + 1 ? 'text-daraja-gold' : 'text-white/20'}`}><div className="w-7 h-7 rounded-full border border-current flex items-center justify-center mono-text text-[9px]">{step > i + 1 ? <Check className="w-3 h-3" /> : i + 1}</div><span className="mono-text text-[8px] uppercase">{label}</span></div>)}</div><div className="border-t border-daraja-border pt-6"><div className="flex items-center gap-2 text-daraja-gold mono-text text-[9px]"><Sparkles className="w-3 h-3" /> LEE-POWERED ATELIER</div><p className="text-white/45 text-sm mt-2">Garment selection determines the measurement model stored in Supabase.</p></div></div>
        {success && <div className="border border-daraja-gold/40 bg-daraja-gold/10 p-6 text-white"><p className="mono-text text-daraja-gold text-[10px]">COMMISSION_ARCHIVED</p><p className="font-serif mt-2">{success.serial_number}</p><p className="text-white/50 text-xs mt-2">Your {success.gender} {success.garment_type} commission is now in the craft ledger.</p></div>}
      </section>

      <section className="lg:col-span-7">
        {step === 1 && <div className="space-y-10"><h2 className="text-3xl font-serif italic text-white">Choose your <span className="text-daraja-gold not-italic">garment</span></h2><div className="space-y-4"><label className="mono-text text-[10px] text-daraja-text-muted uppercase">Client_Profile</label><div className="grid grid-cols-2 gap-3">{['female','male'].map((gender) => <button key={gender} onClick={() => changeGender(gender)} className={`py-5 border mono-text text-[10px] uppercase ${profile.gender === gender ? 'bg-daraja-gold text-daraja-charcoal border-daraja-gold' : 'border-daraja-border text-white/60'}`}>{gender}</button>)}</div></div><div className="space-y-4"><label className="mono-text text-[10px] text-daraja-text-muted uppercase">Garment_Type</label><div className="grid grid-cols-2 md:grid-cols-3 gap-3">{garmentOptions.map((option) => <button key={option.value} onClick={() => update('garmentType', option.value)} className={`py-5 border mono-text text-[10px] uppercase ${profile.garmentType === option.value ? 'bg-daraja-gold text-daraja-charcoal border-daraja-gold' : 'border-daraja-border text-white/60 hover:border-daraja-gold'}`}>{option.label}</button>)}</div></div><div className="space-y-4"><label className="mono-text text-[10px] text-daraja-text-muted uppercase">Body_Type</label><div className="grid grid-cols-4 gap-3">{BODY_TYPES.map((type) => <button key={type} onClick={() => update('bodyType', type)} className={`py-4 border mono-text text-[9px] capitalize ${profile.bodyType === type ? 'bg-daraja-gold text-daraja-charcoal border-daraja-gold' : 'border-daraja-border text-white/60'}`}>{type}</button>)}</div></div><div className="space-y-4"><label className="mono-text text-[10px] text-daraja-text-muted uppercase">Fit_Preference</label><div className="grid grid-cols-4 gap-3">{FIT_PREFS.map((fit) => <button key={fit} onClick={() => update('fitPreference', fit)} className={`py-4 border mono-text text-[9px] capitalize ${profile.fitPreference === fit ? 'bg-daraja-gold text-daraja-charcoal border-daraja-gold' : 'border-daraja-border text-white/60'}`}>{fit}</button>)}</div></div><button onClick={() => setStep(2)} className="w-full py-6 bg-daraja-gold text-daraja-charcoal font-black mono-text text-[10px] flex items-center justify-center gap-3">NEXT_STEP <ArrowRight className="w-4 h-4" /></button></div>}

        {step === 2 && <div className="space-y-10"><div><h2 className="text-3xl font-serif italic text-white">Garment <span className="text-daraja-gold not-italic">Measurements</span></h2><p className="text-white/40 text-sm mt-2">{profile.gender === 'female' ? 'Female' : 'Male'} · {garmentOptions.find((x) => x.value === profile.garmentType)?.label}</p></div><div className="grid grid-cols-2 gap-5">{fields.map((field) => <div key={field.key} className="space-y-2"><label className="mono-text text-[9px] text-daraja-text-muted uppercase">{field.label} (cm)</label><input type="number" min="0" step="0.1" value={profile[field.key]} onChange={(e) => update(field.key, e.target.value)} placeholder="0" className="w-full bg-daraja-charcoal border border-daraja-border p-5 text-white font-mono text-sm focus:border-daraja-gold outline-none" /></div>)}</div><div className="flex gap-4"><button onClick={() => setStep(1)} className="flex-1 py-6 border border-daraja-border text-white mono-text text-[10px]">BACK</button><button onClick={() => setStep(3)} className="flex-[2] py-6 bg-daraja-gold text-daraja-charcoal font-black mono-text text-[10px]">NEXT_STEP</button></div></div>}

        {step === 3 && <div className="space-y-10"><h2 className="text-3xl font-serif italic text-white">Style <span className="text-daraja-gold not-italic">Selection</span></h2><div className="space-y-3"><label className="mono-text text-[10px] text-daraja-text-muted uppercase">Fabric</label><div className="grid grid-cols-2 md:grid-cols-3 gap-3">{FABRICS.map((fabric) => <button key={fabric} onClick={() => update('fabric', fabric)} className={`py-4 border mono-text text-[9px] ${profile.fabric === fabric ? 'bg-daraja-gold text-daraja-charcoal border-daraja-gold' : 'border-daraja-border text-white/60'}`}>{fabric}</button>)}</div></div><div className="grid grid-cols-2 gap-5"><div><label className="mono-text text-[9px] text-daraja-text-muted uppercase">Color</label><input value={profile.color} onChange={(e) => update('color', e.target.value)} placeholder="Deep Indigo, Burnt Gold..." className="mt-2 w-full bg-daraja-charcoal border border-daraja-border p-5 text-white" /></div><div><label className="mono-text text-[9px] text-daraja-text-muted uppercase">Occasion</label><input value={profile.occasion} onChange={(e) => update('occasion', e.target.value)} placeholder="Wedding, Eid, Casual..." className="mt-2 w-full bg-daraja-charcoal border border-daraja-border p-5 text-white" /></div></div><div><label className="mono-text text-[9px] text-daraja-text-muted uppercase">Special Instructions</label><textarea value={profile.specialInstructions} onChange={(e) => update('specialInstructions', e.target.value)} placeholder="Embroidery, lining, finishing, reference details..." className="mt-2 w-full min-h-32 bg-daraja-charcoal border border-daraja-border p-5 text-white resize-none" /></div><div className="flex gap-4"><button onClick={() => setStep(2)} className="flex-1 py-6 border border-daraja-border text-white mono-text text-[10px]">BACK</button><button onClick={() => setStep(4)} className="flex-[2] py-6 bg-daraja-gold text-daraja-charcoal font-black mono-text text-[10px]">REVIEW_ORDER</button></div></div>}

        {step === 4 && <div className="space-y-10"><h2 className="text-3xl font-serif italic text-white">Commission <span className="text-daraja-gold not-italic">Manifest</span></h2><div className="luxury-card p-8 space-y-4">{[['Client',profile.gender],['Garment',garmentOptions.find((x) => x.value === profile.garmentType)?.label],['Body Type',profile.bodyType],['Fit',profile.fitPreference],['Fabric',profile.fabric],['Color',profile.color],['Occasion',profile.occasion]].map(([label,value]) => value ? <div key={label} className="flex justify-between gap-4 border-b border-daraja-border pb-3"><span className="mono-text text-[9px] text-daraja-text-muted uppercase">{label}</span><span className="mono-text text-[9px] text-white text-right">{value}</span></div> : null)}<div className="pt-3"><p className="mono-text text-[9px] text-daraja-text-muted uppercase">Measurements</p><p className="text-white/60 text-xs mt-2">{fields.map((field) => profile[field.key] ? `${field.label}: ${profile[field.key]}cm` : null).filter(Boolean).join(' · ')}</p></div></div><div className="flex gap-4"><button onClick={() => setStep(3)} className="flex-1 py-6 border border-daraja-border text-white mono-text text-[10px]">BACK</button><button onClick={submit} disabled={submitting} className="flex-[2] py-6 bg-daraja-gold text-daraja-charcoal font-black mono-text text-[10px] disabled:opacity-50">{submitting ? 'ARCHIVING...' : 'SUBMIT_COMMISSION'}</button></div></div>}
      </section>
    </div>
  </motion.main>;
}
